import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: `How To's`,
      items: [`How To's/Adopt EIP-4824`, `How To's/DifferentPaths`, `How To's/Add Network Support`, `How To's/reportRegistration`],
    },
    {
      type: 'category',
      label: 'DAOstar API',
      items: ['DAOstar/Overview', 'DAOstar/Service']
    },
    {
      type: 'category',
      label: 'Development',
      items: ['Contract Documentation', 'Contract Registry', 'Tech Infrastructure', 'Backend Infrastructure']
    },
    {
      type: 'category',
      label: 'Standards In Focus',
      items: [
        'Standards In Focus/The DAO API',
        'Standards In Focus/The Grants Metadata Standard',
        'Standards In Focus/What are Standards',
      ],
    },
    {
      type: 'category',
      label: `DAOIP's`,
      items: ['DAOIP/1', 'DAOIP/2', 'DAOIP/3', 'DAOIP/4', 'DAOIP/5','DAOIP/6','DAOIP/7']
    },
    'socials',
    
  ],
   
};

export default sidebars;
